### ISSUE TITLE
Project’s Card | Expand/Collapse Flow

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-rpgf5#5]
****Success Criteria****

1. Each section in the card can expand/collapse. It got triggered by the up dow arrow icon in the row. 
2. While expanding or collapsing, the other card should also collapse OR expand for that section at the same time. 
3. If the user expand or close the details of each MAIN section, it will be saved for all next comparisons. For example, if the user closes the Github, links section, it means he/she is not interested in those details for comparing projects, so it will be closed for both cards and will be closed for coming comparisons.
4. The above case does not apply for Minor sections. 
5. The default view for the card will be all expanded for all sections unless the user has saved a preference to expand/collapse any sections before.

**Comment by mmahdigh** [comment]
> > * [x]   1- The left  project card is scrolled automatically for me
> > 
> > Screen.Recording.2024-09-18.at.3.54.37.PM.mov
> 
> This problem happens again, please take a look @Meriem-BM @mmahdigh
> 
>  Screen.Recording.2024-09-23.at.1.32.20.PM.mov

I can't reproduce this. Chances are it has been fixed accidentally. Could you confirm if it still happens or not?

**Comment by MoeNick** [comment]
Im putting this to QA confirmed as we are close to release @maryjaf If you encounter it again, please raise another issue.
